
services:
  charge_request_service:
    build: ./charge_request_service
    ports:
      - "5000:5000"
    environment:
      LOAD_BALANCER_URL: "http://load_balancer:5000"

  load_balancer:
    build: ./load_balancer
    environment:
      SUBSTATION_HOSTS: "substation1:5000,substation2:5000,substation3:5000"

  substation1:
    build: ./substation_service
  substation2:
    build: ./substation_service
  substation3:
    build: ./substation_service

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning/dashboards
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
